# https://hub.docker.com/r/bitnami/moodle
version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    ports:
      - '8833:3306'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
  moodle:
    image: docker.io/bitnami/moodle:4.2
    ports:
      - '8080:8080'
      - '443:8443'
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - ALLOW_EMPTY_PASSWORD=yes
      - MOODLE_PASSWORD=kialo
      # you can override this by creating a .env file in the same directory as this file with TARGET_KIALO_URL=...
      - TARGET_KIALO_URL=${TARGET_KIALO_URL:-http://localhost:5000}
    volumes:
      - './moodle:/bitnami/moodle'
    depends_on:
      - mariadb
  moodleapp:
    image: moodlehq/moodleapp:latest-dev
    ports:
      - '8100:80'
