name: mod_kialo
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.11
    ports:
      - '8833:3306'
      - '8443:443'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=moodle
      - MARIADB_DATABASE=moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    # liveness probe
    healthcheck:
      test: ["CMD", "mysqladmin", "status", "-uroot"]
      interval: 2s
      timeout: 1s
      retries: 10
  moodle:
    build:
      dockerfile: Dockerfile
      context: moodleimage
      args:
        # main (latest), MOODLE_405_STABLE etc, see https://github.com/moodle/moodle/branches
        MOODLE_BRANCH: ${MOODLE_BRANCH:-main}
        # 7.4, 8.0, 8.1, 8.3 etc., see https://moodledev.io/general/development/policies/php

        PHP_VERSION: ${PHP_VERSION:-8.4}
        # On Linux, if your host user is not the standard 1000:1000, you may need to set these
        # to handle permission issues with the volume mount
        HOST_UID: ${HOST_UID:-1000}
        HOST_GID: ${HOST_GID:-1000}
    ports:
      - '8080:8080'
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - ALLOW_EMPTY_PASSWORD=yes
      - MOODLE_PASSWORD=kialo1234
      # you can override the following by creating a .env file in the same directory as this file
      - TARGET_KIALO_URL=${TARGET_KIALO_URL:-http://localhost:5000}
      - KIALO_IP=${KIALO_IP}
      - MOODLE_HOST=http://${MOODLE_HOST:-localhost:8080}
    volumes:
      - '..:/var/www/html/mod/kialo'
      - /var/www/html/mod/kialo/.git
    depends_on:
      - mariadb
  moodleapp:
    image: moodlehq/moodleapp:latest-dev
    ports:
      - '8100:80'
networks:
  # join the existing network when running Kialo locally
  default:
    name: kialo_default
    external: true
