<?php
// This file is part of Moodle - https://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <https://www.gnu.org/licenses/>.

/**
 * This receives the LTI auth request from Kialo, and redirects to the Kialo activity.
 *
 * @package     mod_kialo
 * @copyright   2023 onwards, Kialo GmbH <support@kialo-edu.com>
 * @license     https://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 *
 * @var moodle_page $PAGE
 * @var core_renderer $OUTPUT
 * @var stdClass $USER
 */

// phpcs:disable moodle.Files.RequireLogin.Missing -- We call require_login in lti_auth helper method below.

require(__DIR__ . '/../../config.php');
require_once(__DIR__ . '/lib.php');
require_once('vendor/autoload.php');

use mod_kialo\kialo_config;
use mod_kialo\kialo_view;
use mod_kialo\lti_flow;
use mod_kialo\output\loading_page;
use mod_kialo\output\repost_page;

// Since MDL-83526 the MoodleSession cookie defaults to SameSite=Lax. When a Kialo discussion is shown
// embedded, Kialo redirects the browser back to this endpoint from within its own (cross-site) iframe,
// so the browser does not send the session cookie and the user appears logged out. Re-issuing the exact
// same request from a page served by Moodle itself makes it a same-site request, so the cookie is sent
// and we can authenticate normally. This mirrors Moodle core's own mod/lti/auth.php (MDL-71887).
if (kialo_view::needs_session_repost()) {
    // Prevent this cookie-less request from setting a fresh (anonymous) session cookie. Otherwise that
    // new cookie would be sent on the repost instead of the user's real session, keeping them logged out.
    header_remove('Set-Cookie');

    $PAGE->set_context(context_system::instance());
    $PAGE->set_url('/mod/kialo/lti_auth.php');
    $PAGE->set_title(get_string('redirect_title', 'mod_kialo'));

    // The repost must reproduce the original request faithfully: same HTTP method, same parameters in
    // the same place. The LTI library reads request parameters method-dependently (query string for
    // GET, request body for POST), so a GET launch reposted as a POST would lose lti_message_hint.
    // Kialo redirects here via GET, so we normally repost as a GET with the parameters in the query.
    if (($_SERVER['REQUEST_METHOD'] ?? 'GET') === 'POST') {
        // Keep the original query string in the action so query parameters are preserved; resubmit the
        // body parameters as hidden fields.
        $reposturl = $_SERVER['REQUEST_URI'] ?? (new moodle_url('/mod/kialo/lti_auth.php'))->out(false);
        $repostmethod = 'post';
        $repostparams = $_POST;
    } else {
        // GET: submit the parameters as form fields so they end up in the query string of the new
        // request. The action must be the bare endpoint URL (a GET form replaces any query string).
        $reposturl = (new moodle_url('/mod/kialo/lti_auth.php'))->out(false);
        $repostmethod = 'get';
        $repostparams = $_GET;
    }

    $output = $PAGE->get_renderer('mod_kialo');
    echo $output->render(new repost_page($reposturl, $repostmethod, $repostparams));
    exit;
}

try {
    $message = lti_flow::lti_auth();
    $redirectform = $message->toHtmlRedirectForm();

    // Workaround for wrong redirect URI generated by the LTI lib, see https://github.com/oat-sa/lib-lti1p3-core/issues/160.
    $tool = kialo_config::get_instance()->create_registration()->getTool();
    $redirectform = preg_replace("/action=\".*?\"/i", 'action="' . $tool->getLaunchUrl() . '"', $redirectform);

    $output = $PAGE->get_renderer('mod_kialo');
    echo $output->render(new loading_page(
        get_string("redirect_title", "mod_kialo"),
        get_string("redirect_loading", "mod_kialo"),
        $redirectform
    ));
} catch (Throwable $e) {
    // Show Moodle's default error page including some debug info.
    throw new \moodle_exception('errors:ltiauth', 'kialo', '', null, $e->getMessage());
}
